version: "3"
formatters:
  enable:
    - gci
    - gofumpt
    - golines
linters:
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
